export const SET_COUNTRIES = 'SET_COUNTRIES';
export const REQUEST_CITIES_SUCCESS = 'REQUEST_CITIES';
export const REQUEST_CITIES_PENDING = 'REQUEST_CITIES_PENDING';
export const REQUEST_CITIES_FAILED = 'REQUEST_CITIES_FAILED';




