export const DISPLAY_SIGNIN_UP_MESSAGE = 'DISPLAY_SIGNIN_UP_MESSAGE';
export const SET_ALL_USER_DETAILS = 'SET_ALL_USER_DETAILS';

export const SET_DAILY_CALORIES_AMOUNT = 'SET_DAILY_CALORIES_AMOUNT';



