export const DISPLAY_SIGNIN_UP_MESSAGE = 'DISPLAY_SIGNIN_UP_MESSAGE';

export const SET_ALL_USER_DETAILS = 'SET_ALL_USER_DETAILS';

export const SET_CALORIES_AMOUNT = 'SET_CALORIES_AMOUNT';

export const SET_ALL_DEFAULT_RECIPES_ARRAY = 'SET_ALL_DEFAULT_RECIPES_ARRAY';

export const CHANGE_CURRENT_CALORIES_AMOUNT = 'CHANGE_CURRENT_CALORIES_AMOUNT';

export const GET_TODAY_RECIPES_ARRAY = 'GET_TODAY_RECIPES_ARRAY';

export const ADD_TO_TODAY_RECIPES_ARRAY = 'ADD_TO_TODAY_RECIPES_ARRAY';

export const SET_SPECIAL_RECIPES_ARRAY = 'SET_SPECIAL_RECIPES_ARRAY';

export const SET_CHOOSEN_RECIPES_ARRAY_IDX = 'SET_CHOOSEN_RECIPES_ARRAY_IDX';

export const MORE_RECPIE_DETAILS = 'MORE_RECPIE_DETAILS';

export const SET_FAVORITES_RECIPES_ARRAY = 'SET_FAVORITES_RECIPES_ARRAY';

export const ADD_TO_FAVORITS_ARRAY = 'ADD_TO_FAVORITS_ARRAY';

export const REMOVE_RECPIE_FROM_FAVORITES_ARRAY = 'REMOVE_RECPIE_FROM_FAVORITES_ARRAY';

export const REMOVE_RECPIE_FROM_DAILY_ARRAY = 'REMOVE_RECPIE_FROM_DAILY_ARRAY';

export const SET_OPERATION = 'SET_OPERATION';