export const DISPLAY_SIGNIN_UP_MESSAGE = 'DISPLAY_SIGNIN_UP_MESSAGE';

export const SET_ALL_USER_DETAILS = 'SET_ALL_USER_DETAILS';

export const SET_CALORIES_AMOUNT = 'SET_CALORIES_AMOUNT';

export const SET_ALL_DEFAULT_RECIPES_ARRAY = 'SET_ALL_DEFAULT_RECIPES_ARRAY';

export const CHANGE_CURRENT_CALORIES_AMOUNT = 'CHANGE_CURRENT_CALORIES_AMOUNT';

export const GET_TODAY_RECIPES_ARRAY = 'GET_TODAY_RECIPES_ARRAY';

export const ADD_TO_TODAY_RECIPES_ARRAY = 'ADD_TO_TODAY_RECIPES_ARRAY';

export const SET_SPECIAL_RECIPES_ARRAY = 'SET_SPECIAL_RECIPES_ARRAY';

export const SET_CHOOSEN_RECIPES_ARRAY_IDX = 'SET_CHOOSEN_RECIPES_ARRAY_IDX';


