export const CURRENT_LOCATION = 'CURRENT_LOCATION';
export const CURRENT_WEATHER = 'CURRENT_WEATHER';
export const SEARCHED_WEATHER = 'SEARCHED_WEATHER'; 
export const SEARCHED_KEY = 'SEARCHED_KEY';
export const API_KEY = 'i1l3M4Wz4GUUMsEVwOQm57YTjyowEfKv';




